# Generated by Django 3.1.7 on 2021-04-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imdb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
