# Generated by Django 3.1.7 on 2021-04-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imdb_app', '0004_auto_20210420_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_model',
            name='user_image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
